# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
    os: "ubuntu-20.04"
    tools:
        python: "3.10"
    commands:
      - python setup.py docbuild

# Build documentation in the docs/ directory with Sphinx
sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: false

# By default readthedocs does not checkout git submodules
submodules:                                                                                                                          
    include: all
