[general] # general setting independent of processing steps
raw_files = 'raw_data/*.silc' # string used to obtain list of raw data files for processing
pixel_size = 24 # pixel size of imaging system in microns

[steps] # setup of analysis pipeline order, functions, and parameters

    [steps.classifier]
    pipeline_class = 'pyopia.classify.Classify'
    model_path = 'keras_model.h5' # path to trained nn model

    [steps.load]
    pipeline_class = 'pyopia.instrument.silcam.SilCamLoad'

    [steps.imageprep]
    pipeline_class = 'pyopia.instrument.silcam.ImagePrep'
    image_level = 'imraw' # the level of processing for further analysis. Either 'imraw' for ignoring background or 'imc' for using the backgroun-corrected image. Defaults to 'imc' if not defined.

    [steps.segmentation]
    pipeline_class = 'pyopia.process.Segment'
    threshold = 0.85 # threshold used for segmentation

    [steps.statextract]
    pipeline_class = 'pyopia.process.CalculateStats'

    [steps.output]
    pipeline_class = 'pyopia.io.StatsH5'
    output_datafile = './test' # prefix path for output nc file